[package]
name = "ubi-tester"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
platforms = "3.2.0"
tempfile = "3.13.0"
tokio = { version = "1.41.0", features = ["full"] }
ubi = "0.2.0"
